server:
  port: 8082
spring:
  application:
    name: coupon-template-serv
  datasource:
    username: root
    password: Lyb1217..
    url: jdbc:mysql://127.0.0.1:3306/geekbang_coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: GeekbangCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.4.125:8848, 172.18.4.125:8948
        service: coupon-template-serv
        heart-beat-timeout: 20000
        heart-beat-interval: 5000

        naming-load-cache-at-start: false
        namespace: dev
        cluster-name: Cluster-A
        group: DEFAULT_GROUP
        register-enabled: true
        username: nacos
        password: Lyb1217..
    sentinel:
      transport:
        dashboard: 172.18.4.125:8080
        port: 8080
      eager: true


