server:
  port: 8083
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  application:
    name: coupon-customer-serv
  datasource:
    # mysql数据源
    username: root
    password: Lyb1217..
    url: jdbc:mysql://127.0.0.1:3306/geekbang_coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: GeekbangCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false

  cloud:
    nacos:
      discovery:
        server-addr: 172.18.4.125:8848, 172.18.4.125:8948
        service: coupon-customer-serv
        heart-beat-timeout: 20000
        heart-beat-interval: 5000

        naming-load-cache-at-start: false
        namespace: dev
        cluster-name: Cluster-A
        group: DEFAULT_GROUP
        register-enabled: true
        username: nacos
        password: Lyb1217..
        enabled: true
        # 添加网络连接相关配置
        watch-delay: 30000
        remote:
          client:
            connect-timeout: 5000
            read-timeout: 5000
    loadbalancer:
      nacos:
        enabled: true
    openfeign:
      client:
        config:
          # 全局超时配置
          default:
            # 网络连接阶段1s超时
            connect-timeout: 1000
            # 服务请求响应阶段5s超时
            read-timeout: 5000
          # 针对某个服务的超时配置
          coupon-template-serv:
            connect-timeout: 1000
            read-timeout: 2000
      circuitbreaker:
        enabled: true

logging:
  level:
    com.alibaba.nacos: debug
    com.yubolee.coupon.customer.feign.TemplateService: debug
    com.yubolee.coupon.customer.feign.CalculationService: debug

